---
title: "Applying immunarch"
author: "Tess Attenborough"
date: "11/06/2020"
output: html_document
---
```{r}
library(dplyr)
library(immunarch)
library("devtools")
library("ggplot2")
library("vegan")
library("ineq")
library("tidyverse")
library("praise")
library("scales")
library("patchwork")
```

```{r}
# first list
data <- list(A1 = A1, A12 = A12, A2 = A2, A3 = A3, A6 = A6, B1 = B1, B2 = B2, C2x = C2x, C2y = C2y, CCORD = CCORD, D1 = D1, D3 = D3, D6CD4 = D6CD4, D6CD8 = D6CD8, D8CD4 = D8CD4, D8CD8 = D8CD8, E1 = E1, E2 = E2, E3 = E3, F1 = F1, F19 = F19, F3 = F3, F6 =F6, G1 = G1, G6 = G6, H1 = H1, H12 = H12, H18 = H18, H2 = H2, H3 = H3, H6 = H6, I12 = I12, I2 = I2, I4 = I4, I6 = I6, J1 = J1, J2 = J2, J3 = J3, K1 = K1, K2 = K2, K3 = K3, L1 = L1, L12 = L12, L2 = L2, L22 = L22, L3 = L3, M1 = M1, M12 = M12, M2 = M2, M22 = M22, M6 = M6, M8 = M8, N1 = N1, N12 = N12, N3 = N3, O12 = O12, O2 = O2, P1 = P1, P12 = P12, P17 = P17, P2 = P2, P3 = P3, P30 = P30, P6 = P6, Q1 = Q1, QCORD = QCORD, R1 = R1, RCORD = RCORD)
# nested lists
betaCDR3dataNoControls <- list(data = data, meta = meta)

exp_vol <- repExplore(alphaCDR3dataNoControls$data, .method = "len", .col = "aa")
p1 <- vis(exp_vol, .by = c("Month.after.transplant"), .meta = alphaCDR3dataNoControls$meta)
p1 


ggsave("alphaCDR3lenNoControl.pdf", width = 35, height = 20, units = c('cm'))
```

```{r}
p2 <- vis(spectratype(alphaCDR3dataNoControls$data[[1]], .quant = "count", .col = "aa")) #this include abundance, like ben did

p2

# Plot 
CB2A_alpha_cdr3$CDR3Len <- nchar(as.character(CB2A_alpha_cdr3$CDR3s))
# Plot for each individual

  cdr3DatTemp <- CB2A_alpha_cdr3
  cdr3DatTemp.expanded <- cdr3DatTemp[rep(row.names(cdr3DatTemp), cdr3DatTemp$Count),]
  ggp <- ggplot(data=cdr3DatTemp.expanded)+
    geom_line(aes(CDR3Len), stat='density')+
    scale_x_continuous(limits=c(0,max(CB2A_alpha_cdr3$CDR3Len)))+
    theme_classic()
  ggp
 
```

```{r}
imm_ov2 <- repOverlap(alphaCDR3dataNoControls$data, .method = "morisita", .verbose = F)
repOverlapAnalysis(imm_ov2, "mds") %>% vis()
```



ok here i am going to make 'spectratypes' of some example samples
normal: G6
abnormal: L1
patient over time

```{r}
# first list
data <- list(A1 = A1, A12 = A12, A2 = A2, A3 = A3, A6 = A6, B1 = B1, B2 = B2, C2x = C2x, C2y = C2y, CCORD = CCORD, D1 = D1, D3 = D3, D6CD4 = D6CD4, D6CD8 = D6CD8, D8CD4 = D8CD4, D8CD8 = D8CD8, E1 = E1, E2 = E2, E3 = E3, F1 = F1, F19 = F19, F3 = F3, F6 =F6, G1 = G1, G6 = G6, H1 = H1, H12 = H12, H18 = H18, H2 = H2, H3 = H3, H6 = H6, I12 = I12, I2 = I2, I4 = I4, I6 = I6, J1 = J1, J2 = J2, J3 = J3, K1 = K1, K2 = K2, K3 = K3, L1 = L1, L12 = L12, L2 = L2, L22 = L22, L3 = L3, M1 = M1, M12 = M12, M2 = M2, M22 = M22, M6 = M6, M8 = M8, N1 = N1, N12 = N12, N3 = N3, O12 = O12, O2 = O2, P1 = P1, P12 = P12, P17 = P17, P2 = P2, P3 = P3, P30 = P30, P6 = P6, Q1 = Q1, QCORD = QCORD, R1 = R1, RCORD = RCORD, T_A = T_A, T_B = T_B, T_B1 = T_B1, T_C2 = T_C2, T_C3 = T_C3, T_C300 = T_C300, T_C400 =T_C400, T_D200 = T_D200, UCB2A = UCB2A, UCB2B = UCB2B, UCB2C = UCB2C, UCB2D = UCB2D, UCB2E = UCB2E, UCB2F = UCB2F)
# nested lists
betaCDR3data <- list(data = data, meta = meta)

# first list
data <- list(L1 = L1)
# nested lists
betaCDR3data <- list(data = data, meta = meta)

repClonality(betaCDR3data$data, "homeo") %>% vis()

p1 <- vis(spectratype(betaCDR3data$data[[1]], .quant = "count", .col = "aa")) #this include abundance, like ben did

p1
fixVis(p1)
# first list
data <- list(G6 = G6)
# nested lists
betaCDR3data <- list(data = data, meta = meta)

repClonality(betaCDR3data$data, "homeo") %>% vis()

p2 <- vis(spectratype(betaCDR3data$data[[1]], .quant = "count", .col = "aa")) #this include abundance, like ben did

p2
fixVis(p2)
# first list
data <- list(H1 = H1, H2 = H2, H3 = H3, H6 = H6, H12 = H12, H18 = H18)
# nested lists
betaCDR3data <- list(data = data, meta = meta)
p3 <- vis(spectratype(betaCDR3data$data[[1]], .quant = "count", .col = "aa")) #this include abundance, like ben did
p3

p4 <- vis(spectratype(betaCDR3data$data[[2]], .quant = "count", .col = "aa")) #this include abundance, like ben did
p4

p5 <- vis(spectratype(betaCDR3data$data[[3]], .quant = "count", .col = "aa")) #this include abundance, like ben did
p5

p6 <- vis(spectratype(betaCDR3data$data[[4]], .quant = "count", .col = "aa")) #this include abundance, like ben did
p6

p7 <- vis(spectratype(betaCDR3data$data[[5]], .quant = "count", .col = "aa")) #this include abundance, like ben did
p7

p8 <- vis(spectratype(betaCDR3data$data[[6]], .quant = "count", .col = "aa")) #this include abundance, like ben did
p8


p2 + p1+ 
  plot_layout(guides = 'collect')


ggsave("normalAndAbnormal.pdf", width = 35, height = 25, units = c('cm'))

p3 + p4+ p5 +p6 + p7+ p8 +
  plot_layout(guides = 'collect', ncol = 2)


ggsave("spectraTypingPatientH.pdf", width = 35, height = 25, units = c('cm'))
```

here 
```{r}
data <- list(A1 = A1, A12 = A12, A2 = A2, A3 = A3, A6 = A6, B1 = B1, B2 = B2, C2x = C2x, C2y = C2y, CCORD = CCORD, D1 = D1, D3 = D3, D6CD4 = D6CD4, D6CD8 = D6CD8, D8CD4 = D8CD4, D8CD8 = D8CD8, E1 = E1, E2 = E2, E3 = E3, F1 = F1, F19 = F19, F3 = F3, F6 =F6, G1 = G1, G6 = G6, H1 = H1, H12 = H12, H18 = H18, H2 = H2, H3 = H3, H6 = H6, I12 = I12, I2 = I2, I4 = I4, I6 = I6, J1 = J1, J2 = J2, J3 = J3, K1 = K1, K2 = K2, K3 = K3, L1 = L1, L12 = L12, L2 = L2, L22 = L22, L3 = L3, M1 = M1, M12 = M12, M2 = M2, M22 = M22, M6 = M6, M8 = M8, N1 = N1, N12 = N12, N3 = N3, O12 = O12, O2 = O2, P1 = P1, P12 = P12, P17 = P17, P2 = P2, P3 = P3, P30 = P30, P6 = P6, Q1 = Q1, QCORD = QCORD, R1 = R1, RCORD = RCORD, T_A = T_A, T_B = T_B, T_B1 = T_B1, T_C2 = T_C2, T_C3 = T_C3, T_C300 = T_C300, T_C400 =T_C400, T_D200 = T_D200, UCB2A = UCB2A, UCB2B = UCB2B, UCB2C = UCB2C, UCB2D = UCB2D, UCB2E = UCB2E, UCB2F = UCB2F)

###alpha
data <- list(A1 = A1, A2 = A2, A3 = A3,  A6 = A6, A12 = A12)
# nested lists
alphaVDJdataA <- list(data = data, meta = meta)

data <- list(D1 = D1, D3 = D3, D6CD4 = D6CD4, D6CD8 = D6CD8, D8CD4 = D8CD4, D8CD8 = D8CD8)

alphaVDJdataD <- list(data = data, meta = meta)

data <- list(F1 = F1, F3 = F3, F6 =F6, F19 = F19)

alphaVDJdataF <- list(data = data, meta = meta)

data <- list(H1 = H1, H2 = H2, H3 = H3, H6 = H6, H12 = H12, H18 = H18)

alphaVDJdataH <- list(data = data, meta = meta)

data <- list(I2 = I2, I4 = I4, I6 = I6, I12 = I12)

alphaVDJdataI <- list(data = data, meta = meta)

data <- list(L1 = L1, L2 = L2, L12 = L12, L22 = L22)

alphaVDJdataL <- list(data = data, meta = meta)

data <- list(M1 = M1, M2 = M2, M6 = M6, M8 = M8, M12 = M12,  M22 = M22)
# nested lists
alphaVDJdataM <- list(data = data, meta = meta)

data <- list(P1 = P1, P2 = P2, P3 = P3, P6 = P6, P17 = P17, P30 = P30)
# nested lists
alphaVDJdataP<- list(data = data, meta = meta)

#beta

data <- list(A1 = A1, A2 = A2, A3 = A3,  A6 = A6, A12 = A12)
# nested lists
betaVDJdataA <- list(data = data, meta = meta)

data <- list(D1 = D1, D3 = D3, D6CD4 = D6CD4, D6CD8 = D6CD8, D8CD4 = D8CD4, D8CD8 = D8CD8)

betaVDJdataD <- list(data = data, meta = meta)

data <- list(F1 = F1, F3 = F3, F6 =F6, F19 = F19)

betaVDJdataF <- list(data = data, meta = meta)

data <- list(H1 = H1, H2 = H2, H3 = H3, H6 = H6, H12 = H12, H18 = H18)

betaVDJdataH <- list(data = data, meta = meta)

data <- list(I2 = I2, I4 = I4, I6 = I6, I12 = I12)

betaVDJdataI <- list(data = data, meta = meta)

data <- list(L1 = L1, L2 = L2, L12 = L12, L22 = L22)

betaVDJdataL <- list(data = data, meta = meta)

data <- list(M1 = M1, M2 = M2, M6 = M6, M8 = M8, M12 = M12,  M22 = M22)
# nested lists
betaVDJdataM <- list(data = data, meta = meta)

data <- list(P1 = P1, P2 = P2, P3 = P3, P6 = P6, P12 = P12, P17 = P17, P30 = P30)
# nested lists
betaVDJdataP<- list(data = data, meta = meta)


p1= repClonality(alphaVDJdataA$data, "homeo") %>% vis()
p1
p2 = repClonality(betaVDJdataA$data, "homeo") %>% vis()


p3 = repClonality(alphaVDJdataM$data, "homeo") %>% vis()
p4 = repClonality(betaVDJdataM$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoA.pdf", width = 35, height = 25, units = c('cm'))


p1= repClonality(alphaVDJdataD$data, "homeo") %>% vis()

p2 = repClonality(betaVDJdataD$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoD.pdf", width = 35, height = 25, units = c('cm'))

p1= repClonality(alphaVDJdataF$data, "homeo") %>% vis()

p2 = repClonality(betaVDJdataF$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoF.pdf", width = 35, height = 25, units = c('cm'))

p1= repClonality(alphaVDJdataH$data, "homeo") %>% vis()

p2 = repClonality(betaVDJdataH$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoH.pdf", width = 35, height = 25, units = c('cm'))

p1= repClonality(alphaVDJdataI$data, "homeo") %>% vis()

p2 = repClonality(betaVDJdataI$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoI.pdf", width = 35, height = 25, units = c('cm'))

p1= repClonality(alphaVDJdataL$data, "homeo") %>% vis()

p2 = repClonality(betaVDJdataL$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoL.pdf", width = 35, height = 25, units = c('cm'))


p1= repClonality(alphaVDJdataM$data, "homeo") %>% vis()

p2 = repClonality(betaVDJdataM$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoM.pdf", width = 35, height = 25, units = c('cm'))

p1= repClonality(alphaVDJdataP$data, "homeo") %>% vis()

p2 = repClonality(betaVDJdataP$data, "homeo") %>% vis()
p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)


ggsave("homeoP.pdf", width = 35, height = 25, units = c('cm'))


```

the home clonality by immune recon
```{r}
immalpha= repClonality(alphaVDJdataNoControls$data, "homeo")
immalpha
vis(immalpha, .by = c("Immune.reconstitution"), .meta = alphaVDJdataNoControls$meta)
ggsave("alphabyImmune.pdf", width = 35, height = 25, units = c('cm'))


immabeta= repClonality(betaVDJdataNoControls$data, "homeo")
immabeta
vis(immabeta, .by = c("Immune.reconstitution"), .meta = betaVDJdataNoControls$meta)
ggsave("betabyImmune.pdf", width = 35, height = 25, units = c('cm'))


```

differenve in v and j gene usage
```{r}
#okay, in A

imm_gu <- geneUsage(alphaVDJdataA$data[c(1, 2, 3, 4, 5)], "hs.trav", .norm = T, .quant = "count")

p1 = vis(imm_gu)
ggsave("alphaVgeneinA.pdf", width = 35, height = 25, units = c('cm'))

imm_gu <- geneUsage(alphaVDJdataA$data[c(1, 2, 3, 4, 5)], "hs.traj", .norm = T, .quant = "count")

p2 = vis(imm_gu)
ggsave("alphaJgeneinA.pdf", width = 35, height = 25, units = c('cm'))

p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)
ggsave("alphageneSinA.pdf", width = 35, height = 25, units = c('cm'))

###
imm_gu <- geneUsage(betaVDJdataA$data[c(1, 2, 3, 4, 5)], "hs.trbv", .norm = T, .quant = "count")

p1 = vis(imm_gu)
ggsave("betaVgeneinA.pdf", width = 35, height = 25, units = c('cm'))

imm_gu <- geneUsage(betaVDJdataA$data[c(1, 2, 3, 4, 5)], "hs.trbj", .norm = T, .quant = "count")

p2 = vis(imm_gu)
ggsave("betaJgeneinA.pdf", width = 35, height = 25, units = c('cm'))

p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)
ggsave("betageneSinA.pdf", width = 35, height = 25, units = c('cm'))


#okay, now in M

imm_gu <- geneUsage(alphaVDJdataM$data[c(1, 2, 3, 4, 5, 6)], "hs.trav", .norm = T, .quant = "count")

p1 = vis(imm_gu)
ggsave("alphaVgeneinM.pdf", width = 35, height = 25, units = c('cm'))

imm_gu <- geneUsage(alphaVDJdataM$data[c(1, 2, 3, 4, 5, 6)], "hs.traj", .norm = T, .quant = "count")

p2 = vis(imm_gu)
ggsave("alphaJgeneinM.pdf", width = 35, height = 25, units = c('cm'))

p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)
ggsave("alphageneSinM.pdf", width = 35, height = 25, units = c('cm'))

imm_gu <- geneUsage(betaVDJdataM$data[c(1, 2, 3, 4, 5, 6)], "hs.trbv", .norm = T, .quant = "count")

p1 = vis(imm_gu)
ggsave("betaVgeneinM.pdf", width = 35, height = 25, units = c('cm'))

imm_gu <- geneUsage(betaVDJdataM$data[c(1, 2, 3, 4, 5, 6)], "hs.trbj", .norm = T, .quant = "count")

p2 = vis(imm_gu)
ggsave("betaJgeneinM.pdf", width = 35, height = 25, units = c('cm'))

p1 + p2 +
  plot_layout(guides = 'collect', ncol = 1)
ggsave("betageneSinM.pdf", width = 35, height = 25, units = c('cm'))

########


imm_gu <- geneUsage(alphaVDJdataNoControls$data, "hs.trav", .norm = T, .quant = "count")

vis(imm_gu, .by = "Immune.reconstitution", .meta = alphaVDJdataNoControls$meta, .plot = "box")
ggsave("alphaVbyImmune.pdf", width = 55, height = 45, units = c('cm'))

imm_gu <- geneUsage(alphaVDJdataNoControls$data, "hs.traj", .norm = T, .quant = "count")

vis(imm_gu, .by = "Immune.reconstitution", .meta = alphaVDJdataNoControls$meta, .plot = "box")
ggsave("alphaJbyImmune.pdf", width = 55, height = 45, units = c('cm'))

imm_gu <- geneUsage(betaVDJdataNoControls$data, "hs.trbv", .norm = T, .quant = "count")
gene_stats()
vis(imm_gu, .by = "Immune.reconstitution", .meta = betaVDJdataNoControls$meta, .plot = "box")
ggsave("betaVbyImmune.pdf", width = 45, height = 35, units = c('cm'))

imm_gu <- geneUsage(betaVDJdataNoControls$data, "hs.trbj", .norm = T, .quant = "count")

vis(imm_gu, .by = "Immune.reconstitution", .meta = betaVDJdataNoControls$meta, .plot = "box")
ggsave("betaJbyImmune.pdf", width = 55, height = 45, units = c('cm'))

imm_gu <- geneUsage(betaVDJdata$data, "hs.trbv", .norm = T, .quant = "count")

vis(imm_gu, .by = "Patient.or.control", .meta = betaVDJdataNoControls$meta, .plot = "box")
ggsave("betaVbypatientControl.pdf", width = 55, height = 45, units = c('cm'))

###jensen shannon diff

imm_gu_js <- geneUsageAnalysis(imm_gu, .method = "js", .verbose = F)
p1 <- vis(imm_gu_js, .title = "Gene usage JS-divergence", .leg.title = "JS", .text.size = 1.5)
p1
ggsave("alphaVbyImmuneJS.pdf", width = 35, height = 25, units = c('cm'))

vis(geneUsageAnalysis(imm_gu, "cosine+hclust", .verbose = F))
ggsave("alphaVbyImmuneHC.pdf", width = 35, height = 25, units = c('cm'))

```

length
```{r}
exp_len <- repExplore(betaCDR3dataNoControls$data, .method = "len", .col = "aa")
p1 <- vis(exp_len, .by = "Immune.reconstitution", .meta = betaCDR3dataNoControls$meta)
p1
ggsave("betaCDR3lensbyImmune.pdf", width = 35, height = 25, units = c('cm'))

```

